[2017-02-22 09:54:01 +0000] [16556] [INFO] Starting gunicorn 19.6.0
[2017-02-22 09:54:01 +0000] [16556] [INFO] Listening at: http://0.0.0.0:3391 (16556)
[2017-02-22 09:54:01 +0000] [16556] [INFO] Using worker: gevent
[2017-02-22 09:54:01 +0000] [16561] [INFO] Booting worker with pid: 16561
Internal Server Error: /app1/login
Traceback (most recent call last):
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/suyuan/ocp/app1/view/_user_view.py", line 29, in login
    params = json.loads(request.body)
  File "/data/suyuan/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Internal Server Error: /app1/login
Traceback (most recent call last):
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/suyuan/ocp/app1/view/_user_view.py", line 29, in login
    params = json.loads(request.body)
  File "/data/suyuan/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Internal Server Error: /app1/get_activities
Traceback (most recent call last):
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/suyuan/ocp/app1/view/activity_view.py", line 42, in get_activities
    params = json.loads(request.body)
  File "/data/suyuan/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Internal Server Error: /app1/get_activities
Traceback (most recent call last):
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/suyuan/ocp/app1/view/activity_view.py", line 42, in get_activities
    params = json.loads(request.body)
  File "/data/suyuan/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 88 - line 1 column 89 (char 87 - 88)
Internal Server Error: /app1/get_activities
Traceback (most recent call last):
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/suyuan/ocp_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/suyuan/ocp/app1/view/activity_view.py", line 42, in get_activities
    params = json.loads(request.body)
  File "/data/suyuan/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/suyuan/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[2017-02-22 03:27:46 +0000] [16561] [INFO] Worker reloading: /data/suyuan/ocp/app1/services.py modified
[2017-02-22 03:27:46 +0000] [16561] [INFO] Worker exiting (pid: 16561)
[2017-02-22 11:27:46 +0000] [16665] [INFO] Booting worker with pid: 16665
[2017-02-22 03:28:01 +0000] [16665] [INFO] Parent changed, shutting down: <Worker 16665>
[2017-02-22 03:28:01 +0000] [16665] [INFO] Worker exiting (pid: 16665)
[2017-02-22 11:28:04 +0000] [16673] [INFO] Starting gunicorn 19.6.0
[2017-02-22 11:28:04 +0000] [16673] [INFO] Listening at: http://0.0.0.0:3391 (16673)
[2017-02-22 11:28:04 +0000] [16673] [INFO] Using worker: gevent
[2017-02-22 11:28:04 +0000] [16678] [INFO] Booting worker with pid: 16678
[2017-02-22 06:26:52 +0000] [16678] [INFO] Worker reloading: /data/suyuan/ocp/app1/views.py modified
[2017-02-22 06:26:52 +0000] [16678] [INFO] Worker exiting (pid: 16678)
[2017-02-22 14:26:52 +0000] [17162] [INFO] Booting worker with pid: 17162
[2017-02-22 06:27:28 +0000] [17162] [INFO] Parent changed, shutting down: <Worker 17162>
[2017-02-22 06:27:28 +0000] [17162] [INFO] Worker exiting (pid: 17162)
[2017-02-22 14:27:31 +0000] [17175] [INFO] Starting gunicorn 19.6.0
[2017-02-22 14:27:31 +0000] [17175] [INFO] Listening at: http://0.0.0.0:3391 (17175)
[2017-02-22 14:27:31 +0000] [17175] [INFO] Using worker: gevent
[2017-02-22 14:27:31 +0000] [17180] [INFO] Booting worker with pid: 17180
